# Generated by Django 4.2.7 on 2023-11-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='artist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='designer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publisher',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
