# Generated by Django 4.2.7 on 2023-11-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0003_alter_boardgame_alternative_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='age_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='complexity_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_time_peroid',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_time_period',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publish_year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
