# Generated by Django 4.2.7 on 2023-11-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0005_alter_comment_rating_alter_gamer_lend_limit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(to='game_board.category'),
        ),
    ]
