# Generated by Django 4.2.7 on 2023-11-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0007_alter_category_options_boardgame_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
