# Generated by Django 4.2.7 on 2023-11-11 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_board', '0009_gamer_bio_gamer_firstname_gamer_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
