# Generated by Django 4.2.7 on 2023-11-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0010_alter_boardgame_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_board.gamer'),
        ),
    ]
