# Generated by Django 4.2.7 on 2023-11-11 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_board', '0011_alter_boardgame_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gamer',
            new_name='Profile',
        ),
    ]
