# Generated by Django 4.2.7 on 2023-11-12 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0019_rename_max_time_peroid_boardgame_max_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='game_board.profile'),
            preserve_default=False,
        ),
    ]
