# Generated by Django 4.2.7 on 2023-11-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0020_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
    ]
