# Generated by Django 4.2.7 on 2023-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0022_comment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='alternative_names',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='artist',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='designer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_time_period',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='publisher',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
