# Generated by Django 4.2.7 on 2023-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0023_alter_boardgame_alternative_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
