# Generated by Django 4.2.7 on 2023-11-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0025_alter_loanrecord_date_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='game_board.category'),
            preserve_default=False,
        ),
    ]
