# Generated by Django 4.2.7 on 2023-11-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0027_remove_boardgame_alternative_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='complexity_rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
