# Generated by Django 4.2.7 on 2023-11-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_board', '0028_alter_boardgame_complexity_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(to='game_board.category'),
        ),
    ]
